# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
  - repository: MyFileApiClientRepo
    type: github
    endpoint: NYCOpportunity
    name: NYCOpportunity/my-file-api-client
    ref: main

trigger:
- dev
- stg
- main

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    deploymentTarget: 'prod'
    awsServiceConnection: 'nyco_devops_service_acct_hhs01'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'stg') }}:
    deploymentTarget: 'stg'
    awsServiceConnection: 'nyco_devops_service_acct_hhs04'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev') }}:
    deploymentTarget: 'dev'
    awsServiceConnection: 'nyco_devops_service_acct_hhs04'

pool: $(POOL_NAME)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- checkout: self
  path: ./my-file-client
  persistCredentials: true
  fetchDepth: 0
  clean: true

- checkout: MyFileApiClientRepo
  path: ./my-file-api-client

- task: AWSShellScript@1
  displayName: 'Deploy UI'
  continueOnError: true
  condition: in(variables['Build.SourceBranchName'], 'dev', 'stg')
  inputs:
    awsCredentials: $(awsServiceConnection)
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      cd $(Agent.BuildDirectory)/my-file-client
      pwd
      ls -al
      export DEPLOYMENT_TARGET=$(deploymentTarget)
      source ./params.env
      printenv
      npm run ci-set-npmrc
      npm install --no-cache
      npm run ci-deploy

- task: AWSShellScript@1
  displayName: 'Update UI App Version'
  continueOnError: true
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  inputs:
    awsCredentials: $(awsServiceConnection)
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      cd $(Agent.BuildDirectory)/my-file-client
      pwd
      ls -al

      echo "gco dev"
      git checkout dev
      git pull origin dev --no-rebase
      echo "npm version patch"
      npm version patch -m "bump to %s - [skip ci]"

      echo "git push --tags"
      git push --tags origin dev

      echo "git push"
      git push origin dev